// This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
export const environment = {
  production: false,
  icons: {
    primary: 'assets/siteLogos/RyanFennessey_logo_black_V2_color.svg',
    secondary: 'assets/siteLogos/RyanFennessey_logo_white_V3_color.svg',
    small: 'assets/siteLogos/RyanFennessey_logo_footer_initials_color.svg',
  },
  apiBaseUrl: 'https://0c5wla1jif.execute-api.us-west-2.amazonaws.com/dev/',
  s3: {
    baseUrl: 'https://ryan-portfolio-bucket.s3.us-east-2.amazonaws.com',
    bucketName: 'ryan-portfolio-bucket',
  },
  useCache: false,
  disableEdit: false,
};