/* tslint:disable */
// @ts-nocheck
const { writeFile, existsSync, mkdirSync } = require('fs');
const { argv } = require('yargs');

require('dotenv').config();

const environment = argv.environment;

// Checks command line argument: `prod` is production
const isProduction = environment === 'prod';

function writeFileUsingFS(targetPath, environmentFileContent) {
  writeFile(targetPath, environmentFileContent, function (err) {
    if (err) {
      console.log(err);
    }
    if (environmentFileContent !== '') {
      console.log(`wrote variables to ${targetPath}`);
    }
  });
}

// path to the `environments` directory
const envDirectory = './src/environments';

// creates the `environments` directory if it does not exist
if (!existsSync(envDirectory)) {
  mkdirSync(envDirectory);
}

// choose the correct targetPath based on the environment chosen
const targetPath = isProduction
  ? './src/environments/environment.prod.ts'
  : './src/environments/environment.ts';


// creates the files with no content
writeFileUsingFS('./src/environments/environment.prod.ts', '');
writeFileUsingFS('./src/environments/environment.ts', '');

// content to be compiled dynamically
const environmentFileContent = `// This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
export const environment = {
  production: ${isProduction},
  icons: {
    primary: 'assets/siteLogos/RyanFennessey_logo_black.svg',
    secondary: 'assets/siteLogos/RyanFennessey_logo_white.svg',
    small: 'assets/siteLogos/RyanFennessey_logo_favicon.svg',
  },
  staticDataKey: 'PorfolioStaticData',
  apiBaseUrl: '${process.env.API_BASE_URL}',
  s3: {
    baseUrl: '${process.env.S3_BASE_URL}',
    bucketName: '${process.env.S3_BUCKET_NAME}',
  },
${isProduction ? 
`  aws: {
    identityPoolId: '',
    defaultRegion: '',
  },
  dynamoDb: {
    region: '',
    pageTable: '',
  },`
  :
`  aws: {
    identityPoolId: '${process.env.AWS_POOL_ID}',
    defaultRegion: '${process.env.AWS_REGION}',
  },
  dynamoDb: {
    region: '${process.env.DYNAMO_REGION}',
    pageTable: '${process.env.DYNAMO_TABLE_NAME}',
  },`
}
};
`;

// appends data into the target file
writeFileUsingFS(targetPath, environmentFileContent);

/* tslint:enable */
